repos:
  - repo: local
    hooks: 
    - id: checks
      name: Checks
      language: system
      pass_filenames: true
      verbose: true
      entry: bash pre_commit_script.sh -td
      #entry: strace -o pre_commit_script.sh.strace -f pre_commit_script.sh -t
